- name: Install Prometheus
  hosts: all
  become: true
  vars:
    prometheus_version: "2.44.0"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    prometheus_data_dir: "/var/lib/prometheus/data"
    prometheus_config_file: "/etc/prometheus/prometheus.yml"
    prometheus_systemd_file: "/etc/systemd/system/prometheus.service"
  tasks:
    - name: Create Prometheus user and group
      group:
        name: "{{ prometheus_group }}"
        state: present
      become: true
    - user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        system: true
        shell: /usr/sbin/nologin
        home: "{{ prometheus_data_dir }}"
        createhome: no
      become: true
    - name: Download and extract Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
      become: true
    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/opt"
        remote_src: yes
        creates: "/opt/prometheus-{{ prometheus_version }}"
      become: true
    - name: Create Prometheus data directory
      file:
        path: "{{ prometheus_data_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
      become: true
    - name: Copy Prometheus configuration file
      copy:
        src: "{{ playbook_dir }}/files/prometheus.yml"
        dest: "{{ prometheus_config_file }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0644"
      become: true
    - name: Copy Prometheus systemd service file
      copy:
        src: "{{ playbook_dir }}/files/prometheus.service"
        dest: "{{ prometheus_systemd_file }}"
        owner: "root"
        group: "root"
        mode: "0644"
      become: true
    - name: Reload systemd and start Prometheus
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: "prometheus.service"
      become: true
